# MetalLB IP Address Pool
# Defines the range of IPs MetalLB can assign to LoadBalancer services
# Network: 10.0.1.0/24 (LAN - pfSense managed)
# Pool range: 10.0.1.100-110 (11 IPs available)

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
  labels:
    app: metallb
spec:
  addresses:
  - 10.0.1.100-10.0.1.110
  autoAssign: true
  avoidBuggyIPs: false
